### ISSUE TITLE
Push new version to puppet's forge

### ISSUE THREAD

**Issue by neomilium** [xaque208/puppet-ssh#47]
Hi,

On puppet forge the 1.2.0 is available but your latest version seems to be 1.3.1.

Any update planned?

Thanks

**Comment by xaque208** [comment]
Hi.  Sure I can push a tag some evening this week.

**Comment by neomilium** [comment]
Great!

**Comment by xaque208** [comment]
`1.4.0` has been tagged from master and pushed to the forge.  Thanks for the prodding.
