### ISSUE TITLE
1.7.1 not available on the puppet forge

### ISSUE THREAD

**Issue by smortex** [xaque208/puppet-ssh#59]
Hi @xaque208,

It looks like the latest tag did not make it to the forge.  The failure reason is unfortunately expired: https://github.com/xaque208/puppet-ssh/runs/3451852655?check_suite_focus=true

Maybe you can re-trigger the action so that we can diagnose the root cause (a "Re-run all jobs" button should be visible on top of the above page)?

**Comment by xaque208** [comment]
I replaced the secret vars for the forge on this project and now I think it should work.  I think let's push a tag and watch the release.  I think the "re-run" also expired, so rolling forward I think is the way.  I've invited you to join the repo too, so I think that should allow you to push a tag.

**Comment by smortex** [comment]
Thanks!

```
git push origin :1.7.1
git push --tags
```

Sill failing unfortunately:

```
Blacksmith::Error: Error uploading ssh to the forge https://forgeapi.puppetlabs.com/v2/releases [401 Unauthorized]: {"message":"401 Unauthorized","errors":["This request requires valid Authorization"]}
```

**Comment by xaque208** [comment]
Okay, this should help.  https://github.com/xaque208/puppet-ssh/pull/60

**Comment by xaque208** [comment]
`v1.7.2` replaces this and is now on the forge.  If this pops up in another repo, I can manage the config for the secrets easily enough now.

**Comment by smortex** [comment]
Awesome! Thanks!
